set nocompatible
filetype plugin indent on
syntax on

set hlsearch
set mouse=a
set nobackup
set noswapfile
set number
set tabstop=4
set shiftwidth=4
set smartcase
set autoindent
set copyindent
set virtualedit=onemore
set gdefault
set backspace=indent,eol,start

colorscheme evening

noremap ; :
noremap <Space> i
noremap <c-p> "+p
vnoremap <c-p> "+p
noremap <c-c> "+y
vnoremap <c-c> "+y
noremap <c-x> "+d
vnoremap <c-x> "+d
noremap <c-d> d
vnoremap <c-d> d
imap <S-Space> <Esc>
imap <C-Space> <Esc>
imap fd <Esc>
noremap h "+

if filereadable("~/config-local/vimrc")
  source ~/config-local/vimrc
endif
